[package]
name = "genomenon"
version = "0.1.0"
authors = ["Mizki SUZUMORI <suzumorimizuki@gmail.com>"]

[dependencies]
csv = "1.0"
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.2"
