[package]
name = "genomenon"
version = "0.1.0"
authors = ["Mizki SUZUMORI <suzumorimizuki@gmail.com>"]

[dependencies]
csv = "1.0"
failure = "0.1"
lazy_static = "1.1"
regex = "1.0"
rmp-serde = "0.13"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"
